In [ ]:
Apple Results:

This analysis is using rbf:
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
-------------
Best SGD Model Parameters:  {'alpha': 0.0001, 'eta0': 0.001, 'max_iter': 10000}
Accuracy:  0.504247572815534
F1 Score:  0.5896534404821697
Precision:  0.49577702702702703
Recall:  0.7273853779429987
Confusion Matrix: 
 [[244 597]
 [220 587]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
-------------
Best SGD Model Parameters:  {'alpha': 0.0001, 'eta0': 0.001, 'max_iter': 10000}
Accuracy:  0.5254854368932039
F1 Score:  0.5495391705069125
Precision:  0.5236004390779363
Recall:  0.5781818181818181
Confusion Matrix: 
 [[389 434]
 [348 477]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
-------------
Best SGD Model Parameters:  {'alpha': 0.0001, 'eta0': 0.001, 'max_iter': 10000}
Accuracy:  0.5509708737864077
F1 Score:  0.6368989205103042
Precision:  0.572310405643739
Recall:  0.7179203539823009
Confusion Matrix: 
 [[259 485]
 [255 649]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
-------------
Best SGD Model Parameters:  {'alpha': 0.0001, 'eta0': 0.001, 'max_iter': 10000}
Accuracy:  0.5679611650485437
F1 Score:  0.6941580756013747
Precision:  0.5867828612926652
Recall:  0.8496319663512093
Confusion Matrix: 
 [[128 569]
 [143 808]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
-------------
Best SGD Model Parameters:  {'alpha': 0.0001, 'eta0': 0.001, 'max_iter': 10000}
Accuracy:  0.5643203883495146
F1 Score:  0.6967905405405406
Precision:  0.5855216465578424
Recall:  0.8602711157455682
Confusion Matrix: 
 [[105 584]
 [134 825]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
Future Predictions:  ['loss', 'loss', 'loss', 'loss', 'loss']
-------------

This analysis is using linear:
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
-------------
Best SGD Model Parameters:  {'alpha': 0.0001, 'eta0': 0.1, 'max_iter': 10000}
Accuracy:  0.5030339805825242
F1 Score:  0.521891418563923
Precision:  0.49337748344370863
Recall:  0.5539033457249071
Confusion Matrix: 
 [[382 459]
 [360 447]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
-------------
Best SGD Model Parameters:  {'alpha': 0.0001, 'eta0': 0.1, 'max_iter': 10000}
Accuracy:  0.5273058252427184
F1 Score:  0.5535816618911176
Precision:  0.525
Recall:  0.5854545454545454
Confusion Matrix: 
 [[386 437]
 [342 483]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
-------------
Best SGD Model Parameters:  {'alpha': 0.0001, 'eta0': 0.1, 'max_iter': 10000}
Accuracy:  0.533373786407767
F1 Score:  0.6009340944473276
Precision:  0.5659824046920822
Recall:  0.6404867256637168
Confusion Matrix: 
 [[300 444]
 [325 579]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
Future Predictions:  ['loss', 'loss', 'loss', 'loss', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
-------------
Best SGD Model Parameters:  {'alpha': 0.0001, 'eta0': 0.1, 'max_iter': 10000}
Accuracy:  0.5600728155339806
F1 Score:  0.6552543984783643
Precision:  0.5980902777777778
Recall:  0.7245005257623555
Confusion Matrix: 
 [[234 463]
 [262 689]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
-------------
Best SGD Model Parameters:  {'alpha': 0.0001, 'eta0': 0.1, 'max_iter': 10000}
Accuracy:  0.5394417475728155
F1 Score:  0.6494226327944572
Precision:  0.5829187396351575
Recall:  0.7330552659019812
Confusion Matrix: 
 [[186 503]
 [256 703]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
Future Predictions:  ['loss', 'loss', 'loss', 'loss', 'loss']
-------------

In [ ]:
# Imports
import numpy as np
import pandas as pd
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score, precision_score, recall_score, confusion_matrix


# Functions to calculate RSI and MACD
def rsi(data, periods=14):
    delta = data['Close'].diff()
    gain, loss = delta.copy(), delta.copy()
    gain[gain < 0] = 0
    loss[loss > 0] = 0

    avg_gain = gain.rolling(window=periods).mean()
    avg_loss = -loss.rolling(window=periods).mean()

    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

def macd(data, short=12, long=26, signal=9):
    exp1 = data['Close'].ewm(span=short, adjust=False).mean()
    exp2 = data['Close'].ewm(span=long, adjust=False).mean()
    macd = exp1 - exp2
    signal_line = macd.ewm(span=signal, adjust=False).mean()
    return macd, signal_line

# Load data
data = pd.read_csv('spy.csv')

# Feature engineering
data['Average'] = (data['Open'] + data['Close'] + data['High'] + data['Low']) / 4
data['HL_PCT'] = (data['High'] - data['Low']) / data['Low']
data['PCT_change'] = (data['Close'] - data['Open']) / data['Open']
data['Volume_pct_change'] = data['Volume'].pct_change()
data['RSI'] = rsi(data)
data['MACD'], data['Signal'] = macd(data)

# Shift the target variable to predict future stock prices
forecast_out = 5
data['Target'] = data['Close'].shift(-forecast_out)

# Calculate price direction variable (1 for gain, 0 for loss)
data['Price_Direction'] = (data['Target'] > data['Close']).astype(int)

data.dropna(inplace=True)

# Split the data into features (X) and target (y) variables
X = data.drop(['Date', 'Close', 'Target', 'Price_Direction', 'Volume'], axis=1)
y = data['Price_Direction']

kernal = ["rbf", "linear"]

tscv = TimeSeriesSplit(n_splits=5)

for item in kernal:
    print(f"This analysis is using {item}:")

    svm_model = SGDClassifier(loss='hinge', penalty='l2')

    param_grid = {
        'alpha': [0.0001, 0.001, 0.01, 0.1, 1],
        'eta0': [0.001, 0.01, 0.1, 1],
        'max_iter': [1000, 5000, 10000],
    }

    # Perform grid search 
    grid_search = GridSearchCV(svm_model, param_grid, cv=tscv, scoring='accuracy')
    grid_search.fit(X, y) 

    # Set model with the best hyperparameters
    best_sgd_model = grid_search.best_estimator_

    for train_index, test_index in tscv.split(X):
      X_train, X_test = X.iloc[train_index], X.iloc[test_index]
      y_train, y_test = y.iloc[train_index], y.iloc[test_index]

      # Feature scaling for current train-test split (prevents data leakage)
      scaler = StandardScaler()
      X_train_scaled = scaler.fit_transform(X_train)
      X_test_scaled = scaler.transform(X_test)

      # Make predictions 
      y_pred = best_sgd_model.predict(X_test_scaled)

      # Calculate performance metrics
      accuracy = accuracy_score(y_test, y_pred)
      f1 = f1_score(y_test, y_pred)
      precision = precision_score(y_test, y_pred)
      recall = recall_score(y_test, y_pred)
      conf_matrix = confusion_matrix(y_test, y_pred)

      # Print the results 
      print("-------------")
      print("Best SGD Model Parameters: ", grid_search.best_params_)
      print("Accuracy: ", accuracy)
      print("F1 Score: ", f1)
      print("Precision: ", precision)
      print("Recall: ", recall)
      print("Confusion Matrix: \n", conf_matrix)

      # Future predictions
      future_dates = 5  
      X_future = X.iloc[test_index[-future_dates:]]
      X_future_scaled = scaler.transform(X_future)  # Scale the future data using the same scaler
      future_predictions = best_sgd_model.predict(X_future_scaled)

      # Convert predicted directions to gain/loss
      future_directions = ['gain' if direction == 1 else 'loss' for direction in future_predictions]

      print("Future Predictions: ", future_directions)
      print("-------------")
      print("")

This analysis is using rbf:


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SGDClassifi

-------------
Best SGD Model Parameters:  {'alpha': 0.1, 'eta0': 0.01, 'max_iter': 10000}
Accuracy:  0.4996028594122319
F1 Score:  0.6663135593220338
Precision:  0.4996028594122319
Recall:  1.0
Confusion Matrix: 
 [[  0 630]
 [  0 629]]
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

-------------
Best SGD Model Parameters:  {'alpha': 0.1, 'eta0': 0.01, 'max_iter': 10000}
Accuracy:  0.5845909451945989
F1 Score:  0.737844611528822
Precision:  0.5845909451945989
Recall:  1.0
Confusion Matrix: 
 [[  0 523]
 [  0 736]]
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

-------------
Best SGD Model Parameters:  {'alpha': 0.1, 'eta0': 0.01, 'max_iter': 10000}
Accuracy:  0.5710881652104846
F1 Score:  0.7269969666329626
Precision:  0.5710881652104846
Recall:  1.0
Confusion Matrix: 
 [[  0 540]
 [  0 719]]
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

-------------
Best SGD Model Parameters:  {'alpha': 0.1, 'e

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SGDClassifi