In [ ]:
Apple Results:

This analysis is using rbf:
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
-------------
Best SVM Model Parameters:  {'C': 0.1, 'gamma': 0.0001}
Accuracy:  0.48968446601941745
ROC AUC Score:  0.47544007767940155
F1 Score:  0.6574338085539715
Precision:  0.48968446601941745
Recall:  1.0
Confusion Matrix: 
 [[  0 841]
 [  0 807]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
-------------
Best SVM Model Parameters:  {'C': 0.1, 'gamma': 0.0001}
Accuracy:  0.5006067961165048
ROC AUC Score:  0.5295570529106374
F1 Score:  0.6672058228871816
Precision:  0.5006067961165048
Recall:  1.0
Confusion Matrix: 
 [[  0 823]
 [  0 825]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
-------------
Best SVM Model Parameters:  {'C': 0.1, 'gamma': 0.0001}
Accuracy:  0.5485436893203883
ROC AUC Score:  0.51520720334951
F1 Score:  0.7084639498432602
Precision:  0.5485436893203883
Recall:  1.0
Confusion Matrix: 
 [[  0 744]
 [  0 904]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
-------------
Best SVM Model Parameters:  {'C': 0.1, 'gamma': 0.0001}
Accuracy:  0.5770631067961165
ROC AUC Score:  0.45400899453418353
F1 Score:  0.7318199307425933
Precision:  0.5770631067961165
Recall:  1.0
Confusion Matrix: 
 [[  0 697]
 [  0 951]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
-------------
Best SVM Model Parameters:  {'C': 0.1, 'gamma': 0.0001}
Accuracy:  0.5819174757281553
ROC AUC Score:  0.5111305166393997
F1 Score:  0.7357115458381281
Precision:  0.5819174757281553
Recall:  1.0
Confusion Matrix: 
 [[  0 689]
 [  0 959]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

This analysis is using linear:
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
-------------
Best SVM Model Parameters:  {'C': 0.001, 'gamma': 0.0001}
Accuracy:  0.48968446601941745
ROC AUC Score:  0.47709326979889105
F1 Score:  0.6574338085539715
Precision:  0.48968446601941745
Recall:  1.0
Confusion Matrix: 
 [[  0 841]
 [  0 807]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
-------------
Best SVM Model Parameters:  {'C': 0.001, 'gamma': 0.0001}
Accuracy:  0.5006067961165048
ROC AUC Score:  0.46261349828786036
F1 Score:  0.6672058228871816
Precision:  0.5006067961165048
Recall:  1.0
Confusion Matrix: 
 [[  0 823]
 [  0 825]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
-------------
Best SVM Model Parameters:  {'C': 0.001, 'gamma': 0.0001}
Accuracy:  0.5485436893203883
ROC AUC Score:  0.5330133694928156
F1 Score:  0.7084639498432602
Precision:  0.5485436893203883
Recall:  1.0
Confusion Matrix: 
 [[  0 744]
 [  0 904]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
-------------
Best SVM Model Parameters:  {'C': 0.001, 'gamma': 0.0001}
Accuracy:  0.5770631067961165
ROC AUC Score:  0.5242506943532972
F1 Score:  0.7318199307425933
Precision:  0.5770631067961165
Recall:  1.0
Confusion Matrix: 
 [[  0 697]
 [  0 951]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
-------------
Best SVM Model Parameters:  {'C': 0.001, 'gamma': 0.0001}
Accuracy:  0.5819174757281553
ROC AUC Score:  0.4923935037555751
F1 Score:  0.7357115458381281
Precision:  0.5819174757281553
Recall:  1.0
Confusion Matrix: 
 [[  0 689]
 [  0 959]]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

SyntaxError: ignored

In [ ]:
# Imports
import numpy as np
import pandas as pd
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score, precision_score, recall_score, confusion_matrix


# Functions to calculate RSI and MACD
def rsi(data, periods=14):
    delta = data['Close'].diff()
    gain, loss = delta.copy(), delta.copy()
    gain[gain < 0] = 0
    loss[loss > 0] = 0

    avg_gain = gain.rolling(window=periods).mean()
    avg_loss = -loss.rolling(window=periods).mean()

    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

def macd(data, short=12, long=26, signal=9):
    exp1 = data['Close'].ewm(span=short, adjust=False).mean()
    exp2 = data['Close'].ewm(span=long, adjust=False).mean()
    macd = exp1 - exp2
    signal_line = macd.ewm(span=signal, adjust=False).mean()
    return macd, signal_line

# Load data
data = pd.read_csv('spy.csv')

# Feature engineering
data['Average'] = (data['Open'] + data['Close'] + data['High'] + data['Low']) / 4
data['HL_PCT'] = (data['High'] - data['Low']) / data['Low']
data['PCT_change'] = (data['Close'] - data['Open']) / data['Open']
data['Volume_pct_change'] = data['Volume'].pct_change()
data['RSI'] = rsi(data)
data['MACD'], data['Signal'] = macd(data)

# Shift the target variable to predict future stock prices
forecast_out = 5
data['Target'] = data['Close'].shift(-forecast_out)

# Calculate price direction variable (1 for gain, 0 for loss)
data['Price_Direction'] = (data['Target'] > data['Close']).astype(int)

data.dropna(inplace=True)

# Split the data into features (X) and target (y) variables
X = data.drop(['Date', 'Close', 'Target', 'Price_Direction', 'Volume'], axis=1)
y = data['Price_Direction']

kernal = ["rbf", "linear"]

tscv = TimeSeriesSplit(n_splits=5)

for item in kernal:
    print(f"This analysis is using {item}:")

    svm_model = SVC(kernel=item, probability=True)

    param_grid = {
        'C': [0.001, 0.01, 0.1, 1, 10],
        'gamma': [0.0001, 0.001, 0.01, 0.1, 1, 10, 100],
    }

    # Perform grid search 
    grid_search = GridSearchCV(svm_model, param_grid, cv=tscv, scoring='accuracy')
    grid_search.fit(X, y)  

    # Set model with the best hyperparameters
    best_svm_model = grid_search.best_estimator_

    for train_index, test_index in tscv.split(X):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        # Feature scaling for current train-test split (prevents data leakage)
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_test_scaled = scaler.transform(X_test)

        # Make predictions 
        y_pred = best_svm_model.predict(X_test_scaled)
        y_pred_proba = best_svm_model.predict_proba(X_test_scaled)[:, 1]

        # Calculate performance metrics
        accuracy = accuracy_score(y_test, y_pred)
        roc_auc = roc_auc_score(y_test, y_pred_proba)
        f1 = f1_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        conf_matrix = confusion_matrix(y_test, y_pred)

        # Print the results 
        print("-------------")
        print("Best SVM Model Parameters: ", grid_search.best_params_)
        print("Accuracy: ", accuracy)
        print("ROC AUC Score: ", roc_auc)
        print("F1 Score: ", f1)
        print("Precision: ", precision)
        print("Recall: ", recall)
        print("Confusion Matrix: \n", conf_matrix)

        # Future predictions
        future_dates = 5 
        X_future = X.iloc[test_index[-future_dates:]]
        X_future_scaled = scaler.transform(X_future)  # Scale the future data using the same scaler
        future_predictions = best_svm_model.predict(X_future_scaled)

        # Convert predicted directions to gain/loss
        future_directions = ['gain' if direction == 1 else 'loss' for direction in future_predictions]

        print("Future Predictions: ", future_directions)
        print("-------------")
        print("")

This analysis is using rbf:


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


-------------
Best SVM Model Parameters:  {'C': 0.001, 'gamma': 0.0001}
Accuracy:  0.4996028594122319
ROC AUC Score:  0.5088954500719207
F1 Score:  0.6663135593220338
Precision:  0.4996028594122319
Recall:  1.0
Confusion Matrix: 
 [[  0 630]
 [  0 629]]
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------



/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


-------------
Best SVM Model Parameters:  {'C': 0.001, 'gamma': 0.0001}
Accuracy:  0.5845909451945989
ROC AUC Score:  0.5023510890348325
F1 Score:  0.737844611528822
Precision:  0.5845909451945989
Recall:  1.0
Confusion Matrix: 
 [[  0 523]
 [  0 736]]
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------



/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


-------------
Best SVM Model Parameters:  {'C': 0.001, 'gamma': 0.0001}
Accuracy:  0.5710881652104846
ROC AUC Score:  0.5259825889867614
F1 Score:  0.7269969666329626
Precision:  0.5710881652104846
Recall:  1.0
Confusion Matrix: 
 [[  0 540]
 [  0 719]]
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------



/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


-------------
Best SVM Model Parameters:  {'C': 0.001, 'gamma': 0.0001}
Accuracy:  0.6227164416203336
ROC AUC Score:  0.46896616541353386
F1 Score:  0.7674987763093489
Precision:  0.6227164416203336
Recall:  1.0
Confusion Matrix: 
 [[  0 475]
 [  0 784]]
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------



/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


-------------
Best SVM Model Parameters:  {'C': 0.001, 'gamma': 0.0001}
Accuracy:  0.5996822875297856
ROC AUC Score:  0.4761799642594345
F1 Score:  0.7497517378351539
Precision:  0.5996822875297856
Recall:  1.0
Confusion Matrix: 
 [[  0 504]
 [  0 755]]
Future Predictions:  ['gain', 'gain', 'gain', 'gain', 'gain']
-------------

This analysis is using linear:


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
